### ISSUE TITLE
Official basic and advanced structures link broken

### ISSUE THREAD

**Issue by ascalabro** [iJackUA/awesome-yii#10]
In README.md, two links in the first line under "Project structure examples" - "basics" and "advanced" return a 404 not found response. See screenshot below. They are underlined in red.

![Screenshot](http://i.imgur.com/pCfySL9.jpg)

**Comment by samdark** [comment]
Which "Project structure examples" do you mean?

**Comment by ascalabro** [comment]
I've updated my comment on the issue with a screenshot. You should be able to tell from that. 
Thanks,

**Comment by iJackUA** [comment]
Thanks, fixed
seem like there is not special section for basic app in docs
